version: "3.5"
services:
  postgres:
    image: 'postgres:16'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }
